### ISSUE TITLE
Mention on which Path tests are published and what you need to fix in your PEST.php

### ISSUE THREAD

**Issue by StanBarrows** [codebar-ag/laravel-auth#21]
If you not adding Auth to Pest Path it will fail. Please mention that it publishes tests to Auth and that you need to take care about this as well.

`uses(TestCase::class, FastRefreshDatabase::class)->in('Auth','Feature', 'Nova', 'Unit', 'Core');`

**Comment by RhysLees** [comment]
This is automatic
