### ISSUE TITLE
Test does not work on published Testsuite

### ISSUE THREAD

**Issue by StanBarrows** [codebar-ag/laravel-auth#22]
<img width="2055" alt="CleanShot 2023-09-20 at 14 48 56@2x" src="https://github.com/codebar-ag/laravel-auth/assets/10268813/b6cf80d3-7aad-4769-aec8-5093764218c9">

**Comment by RhysLees** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbks3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--59c686052d29003a90741e62719d9fd5ed1e7b0f/image.png)


can replicate
maybe check 
```
/*
    |--------------------------------------------------------------------------
    | Password Reset Settings
    |--------------------------------------------------------------------------
    | By default, the package will use the password_resets table.
    | You may define a different table name here.
    |
    */
    'password_reset_table' => 'password_resets',
```
this is the table name for your password_resets laravel has renamed it in diffrent versions
