### ISSUE TITLE
Authorize With Account that is not allowed to login

### ISSUE THREAD

**Issue by StanBarrows** [codebar-ag/laravel-auth#26]
You can test it out in the immo.space project (website)

<img width="2084" alt="CleanShot 2023-09-22 at 14 36 19@2x" src="https://github.com/codebar-ag/laravel-auth/assets/10268813/adc2b136-79ef-4f6a-9a58-f01659778528">

https://flareapp.io/errors/4202587-client-error-get-httpsgraphmicrosoftcomv10me24selectid2cdisplayname2cbusinessphones2cgivenname2cjobt.../244091685

**Comment by RhysLees** [comment]
<img width="662" alt="image" src="https://github.com/codebar-ag/laravel-auth/assets/43909932/97796a49-7bd8-4887-b483-7edfd3747226">
