### ISSUE TITLE
Feedback v1

### ISSUE THREAD

**Issue by StanBarrows** [codebar-ag/laravel-auth#4]
- [x] Fix Head Badges
<img width="706" alt="CleanShot 2023-09-07 at 17 33 14@2x" src="https://github.com/codebar-ag/laravel-auth/assets/10268813/372c067e-c679-4d70-b784-a0e083fa6536">

---

- [x] Rename What is Laravel Auth?:
Laravel Auth is an internal Laravel Nova Authentication replacement to gain more control over authorizing into Laravel Nova.

---

- [x] Rename it to **_laravel-auth-assets_**

`      "@php artisan vendor:publish --tag=auth-assets --ansi --force",`

---

- [x] Rename it to **laravel-auth:install**

`php artisan auth:install`

---

- [x] Maybe explain a little more whats before and after (What exactly needs to be removed?) 

```
        Nova::routes()
            ->withAuthenticationRoutes()
            ->withPasswordResetRoutes();
```

---

- [x] Invalid Example .env file

<img width="964" alt="CleanShot 2023-09-07 at 17 42 11@2x" src="https://github.com/codebar-ag/laravel-auth/assets/10268813/2655ea3d-7926-4f00-b9c5-0e36abfd82fb">

---

- [x] Switch to named route

```
    Nova::userMenu(function (Request $request, Menu $menu) {
            return $menu
                ->append(MenuItem::externalLink('Logout', '/auth/logout'));
        });
```

---

- [x] rename to --tag=laravel-auth-config

`php artisan vendor:publish --tag=auth-config`

---

- [ ] How to manage translations?
---

- [x] Logo Optional 

<img width="1586" alt="CleanShot 2023-09-07 at 17 49 12@2x" src="https://github.com/codebar-ag/laravel-auth/assets/10268813/3f34dda8-7d38-480a-9bd4-262236024d49">

---

- [x] Adjust initial Logo size about -50% 

---

- [x] Social Button Gray instead of blue

<img width="678" alt="CleanShot 2023-09-07 at 17 50 27@2x" src="https://github.com/codebar-ag/laravel-auth/assets/10268813/abf2269e-a5c4-4ed0-969a-7af6b283b801">

---

- [ ] How to make services optional? there needs to be a way to enable disable it.

---

- [x] Define Redirect Path after Login + Logout
---

- [x] Two Logout Items

` Nova::routes();`

<img width="524" alt="CleanShot 2023-09-07 at 18 15 56@2x" src="https://github.com/codebar-ag/laravel-auth/assets/10268813/092dd225-e05a-4e4f-b521-b0376f9b750c">

And if I remove the extra Menu Item its only one but this does not work.

<img width="428" alt="CleanShot 2023-09-07 at 18 17 16@2x" src="https://github.com/codebar-ag/laravel-auth/assets/10268813/1e98d5cb-4ffd-4501-8525-138cc35da0a7">

**Comment by RhysLees** [comment]
Moved unchecked issues to seperate issues
